### ISSUE TITLE
[PUB] Hanze persons in sources

### ISSUE THREAD

**Issue by fako** [surfedushare/sources-middleware#12]
Hierbij de endpoints voor het ophalen van de Person informatie van de Hanzehogeschool:

Persons: https://hanzetest.azure-api.net/nppo/persons

Alle users:               [https://hanzetest.azure-api.net/nppo/users](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhanzetest.azure-api.net%2Fnppo%2Fusers&data=05%7C01%7Ch.haak-ottens%40pl.hanze.nl%7Cb2bde945b8334314218208db3438a803%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C638161190158583767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X8j%2BXD2KrdIBXdvQ%2B74zUk%2FL3i2RQHfgRccl7e%2BvxNQ%3D&reserved=0)

Een specifieke user:    [https://hanzetest.azure-api.net/nppo/users/7b23d0e6-7805-43c8-b60f-e6d92a4e0d48](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhanzetest.azure-api.net%2Fnppo%2Fusers%2F7b23d0e6-7805-43c8-b60f-e6d92a4e0d48&data=05%7C01%7Ch.haak-ottens%40pl.hanze.nl%7Cb2bde945b8334314218208db3438a803%7Ca3b390147adc48faa11437c2434dbd69%7C0%7C0%7C638161190158583767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FBK0YjgWa4Cl7vz4ReiqBsvJ27E%2Bc6DSND4luFtSkuk%3D&reserved=0)

Waarbij de ‘uuid’ de interne user ID is uit Pure. En de user gebruikt moet worden voor het ophalen van alle e-mailadressen.

Voor allee URL’s geldt dat dezelfde ‘Ocp-Apim-Subscription-Key’ meegestuurd moet worden om de aanroep te mogen uitvoeren als voor de al aangeleverde endpoints.

**Comment by kallepronk** [comment]
https://github.com/surfedushare/sources-middleware/blob/master/api/sources/extraction/hva.py 
Example file, same paradigm so it can nearly be completely copied over

**Comment by kallepronk** [comment]
https://github.com/surfedushare/sources-middleware/blob/master/api/api/settings.py#L290-L323
Add hanze settings

**Comment by kallepronk** [comment]
https://github.com/surfedushare/sources-middleware/blob/f414e54012f6c5faf63a8f261c2483d45bd10e0c/api/core/proxy.py
Proxy class, will make the requests to the source and return the data, builds extractor

**Comment by fako** [comment]
Systeem setup staat beschreven in: https://github.com/surfedushare/sources-middleware/issues/4#issuecomment-1542231527
