### ISSUE TITLE
[KOP#13, PUB#751] Research themes for projects (Hanze)

### ISSUE THREAD

**Issue by fako** [surfedushare/sources-middleware#4]
[Koppeling #13](https://gitlab.surf.nl/publinova-group/koppelingen/-/issues/13)
[Publinova #751](https://gitlab.surf.nl/publinova-group/project-main/-/issues/751)

**Comment by fako** [comment]
@JohnMeurs roep maar een prioriteit. Staat nu op "normal"

**Comment by kallepronk** [comment]
https://github.com/surfedushare/harvester/blob/acceptance/harvester/sources/extraction/hanze/extractor.py#L268-L278
This code should be able to be copied verbatim  🤞🏻

**Comment by fako** [comment]
Belangrijk om nog een keer op development branch te pullen voordat je begint. Verder moet in je .env file staan dat AWS_PROFILE=pol-dev. Waarschijnlijk is dat al zo, maar toch even heads-up voor de zekerheid. Na elke .env verandering altijd nieuwe terminal starten en source activate.sh, zodat envs goed worden ingelezen

**Comment by fako** [comment]
Waiting for response from Hanze about missing ASJCSubjectAreas keywords

**Comment by fako** [comment]
Projects is not using ASJCSubjectAreas, but a different translation table. Projects should look at research_focus_area and use its own much smaller translation table: 

[Vertaaltabellen thema's Pure HG - Publinova_v1.0 (1).xlsx](https://github.com/surfedushare/sources-middleware/files/11891646/Vertaaltabellen.thema.s.Pure.HG.-.Publinova_v1.0.1.xlsx)

**Comment by fako** [comment]
It is correct that not all research_focus_area's have a translation to a research_theme

**Comment by fako** [comment]
Goedgekeurd door John
