### ISSUE TITLE
[PUB] HKU transform string to array in case of single value for Skills and Themes

### ISSUE THREAD

**Issue by mlagerwerf** [surfedushare/sources-middleware#60]
Importing persons from the HKU is stopped because skills is a string instead of an array in the case of a single value. 

This is also the case for themes.

Can you transform the string to an array so the import will no longer stop causing missing data.

**Comment by fako** [comment]
@mlagerwerf ready for testing: https://sources.acc.publinova.nl/api/v1/entities/persons/hku/

Contacts/owners: https://sources.acc.publinova.nl/api/v1/entities/projects/hku/

**Comment by fako** [comment]
@mlagerwerf @peterdubbeldsurf deployed to prod
