### ISSUE TITLE
[PUB] HKU transform string to array in case of single value for Keywords

### ISSUE THREAD

**Issue by mlagerwerf** [surfedushare/sources-middleware#61]
Recently you made a fix for Skills and Themes, now I'm getting projects from the HKU with a single Keywords that is a string as well. Could you make the same change so the the string is transformed to an array?

**Comment by fako** [comment]
Ready for testing: https://sources.acc.publinova.nl/api/v1/entities/projects/hku/

**Comment by mlagerwerf** [comment]
Test OK.
