### ISSUE TITLE
Try to fix multiple problems with files coming from Pure

### ISSUE THREAD

**Issue by fako** [surfedushare/sources-middleware#66]

**Comment by fako** [comment]
Problem occurs when "proxy files" is enabled for HvA

**Comment by peterdubbeldsurf** [comment]
TimeBox 4h for research. Demo environment needed for testing.

**Comment by fako** [comment]
There are a lot of file warnings. How are we going to fix this on the source side?
* https://surf-eduservices.sentry.io/issues/4266795277/?project=4505125577228288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0
* https://surf-eduservices.sentry.io/issues/4315832354/?project=4505125577228288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=2
* https://surf-eduservices.sentry.io/issues/4277043650/?project=4505125577228288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=4

I get the feeling this is very much related to the write errors. Those seem to be failed Sentry logging attempts. How are we making this more sustainable? What is the frontend doing??

**Comment by fako** [comment]
We are going to try to solve Pure image problems and expect these errors to go away or dramatically reduce. Renaming ticket to reflect this.

**Comment by fako** [comment]
We should test a complete reset

**Comment by fako** [comment]
We should also test streaming on frontend

**Comment by fako** [comment]
Playback van videos werkt, maar er is geen streaming. Dit zal geimplementeerd moeten worden in de frontend, maar de stream hopt dan via 4 "servers". De AWS balancer, de Nginx frontend, de UWSGI backend en Pure. Waarschijnlijk heeft Pure ook nog balancers en verschillende middleware. Dit is in ieder geval het geval bij Hanze, die een eigen middleware tussen Pure en de Harvester heeft gezet.

Hanze voorbeeld: https://client.publinova.acc.surf.zooma.cloud/product/de-gebiedscooperatie-als-model-voor-leven-lang-ontwikkelen
