### ISSUE TITLE
Hanze changes for persons

### ISSUE THREAD

**Issue by fako** [surfedushare/sources-middleware#68]

**Comment by peterdubbeldsurf** [comment]
![Image](https://github.com/surfedushare/sources-middleware/assets/144684797/574c551a-3d88-4bc0-acae-4396dffa594e)

**Comment by fako** [comment]
Example file that should be marked 404, but isn't
hanze:hanze:c4a62181-503a-401c-9e85-31e1e5001d89:0f8e26176a23faa76e0a43adffc1badee48e98e5

**Comment by fako** [comment]
Ja, wacht nog maar even met de spritsen. Ik kom nog wat dingen tegen. Ik zal het in ieder geval zo goed mogelijk doen en daarna moeten we weer met Hanze in gesprek ben ik bang.
[10:05](https://publinova.slack.com/archives/C06VDAQP04T/p1713945939444719)
Een ding is bijvoorbeeld dat die Hanze descriptions allerlei HTML bevat. Met name <p> tags. Moet ik die HTML dan strippen en de \n\n toepassen?
:+1:
1

[10:06](https://publinova.slack.com/archives/C06VDAQP04T/p1713945980497379)
Double newline in aanwezigheid van <p> heeft namelijk geen effect
[10:06](https://publinova.slack.com/archives/C06VDAQP04T/p1713946005684069)
Dus waarom descriptions samenvoegen met \n\n als er HTML in de descriptions staat?
[10:07](https://publinova.slack.com/archives/C06VDAQP04T/p1713946068064199)
Ik zal voor nu wel even strippen en concaten met newlines, omdat niet alles HTML is, maar het is wel een beetje een zooitje (edited) 
[10:08](https://publinova.slack.com/archives/C06VDAQP04T/p1713946116947419)
creative_works als custom field bestaat ook niet de de data
[10:08](https://publinova.slack.com/archives/C06VDAQP04T/p1713946122852889)
Maar verder lukt het wel geloof ik

**Comment by fako** [comment]
CSV that indicates missing files:

[hanze-missing-files.csv](https://github.com/surfedushare/sources-middleware/files/15307034/hanze-missing-files.csv)

CSV that indicates forbidden files:

[hanze-forbidden-files.csv](https://github.com/surfedushare/sources-middleware/files/15307039/hanze-forbidden-files.csv)

**Comment by fako** [comment]
Example of a PDF document without any previews: https://client.publinova.acc.surf.zooma.cloud/product/the-heritage-of-captains-on-wadden-sea-islands-valuation-by-laypersons-on-three-spatial-levels

SRN: hanze:hanze:3ade0438-8b6f-40d7-9ccc-b56caeffcb81

**Comment by fako** [comment]
For Hanze files we could use a real title instead of a filename as the "title"

**Comment by fako** [comment]
Missing person information:
- [ ] email
- [ ] phone
- [ ] freeKeywords => skills

**Comment by fako** [comment]
Continue on new board. Needs changes from Hanze.
